"""add device_id to attendance_records

Revision ID: 59c53f6c251d
Revises: 2cf71edda688
Create Date: 2025-10-14 20:56:29.252042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c53f6c251d'
down_revision: Union[str, Sequence[str], None] = '2cf71edda688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'attendance_records', 'devices', ['device_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_column('attendance_records', 'device_id')
    # ### end Alembic commands ###
